name:                test0
version:             0.1.0.0
github:              "githubuser/test0"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test0#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1 && < 1.3
- process
- array

library:
  source-dirs:
  - src
  - ../Lava2021/Modules

executables:
  test0-exe:
    main:                Main.hs
    source-dirs:
    - app
    - ../Lava2021/Modules
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test0

tests:
  test0-test:
    main:                Spec.hs
    source-dirs:
    - test
    - ../Lava2021/Modules
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test0
